---
dispatch:
    uri pages:
        index: index
        "404_file_not_found": file_not_found
        "index.php?XDEBUG_SESSION_START=oqMeo1k2031": index
        "index.php?XDEBUG_SESSION_STOP=oqMeo1k2031": index
    pages uri:
        index: index
        file_not_found: "404_file_not_found"
    default page: index
    file not found page: file_not_found

database:
    host: localhost
    username: aomebo
    password: A0m3b0
    database: aomebo_testing
    site table prefix: site_

feedback:
    error reporting: 32767
    display errors: true
    display startup errors: true
    log errors: true
    error log: Logs/errors.txt
    debug mode: false

session:
    cookie key: aom
    cookie delimiter: _
    cookie path: /
    expires: 1800

site:
    salt: "mkamkem2ok2o1k"
    title: Aomebo Framework Setup
    title delimiter: " - "
    title direction: prepend
    slogan: "The MVC framework"
    shortcut icon: images/shortcut-icon.ico
    show generator: false
    description:
    keywords: etc
    default time-zone: Europe/Stockholm
    session-handler:
    protocol: http
    protocol version: 1.1,
    server name: aomebo.cvj.se
    mod_rewrite: true

session:
    always use session: true
